ARG NGINX_VERSION=1.19.7
FROM soulteary/prebuilt-nginx-modules:base-${NGINX_VERSION}-alpine AS Builder

ARG MODULE_CHECKSUM=e85d50198b1ce659828503f001ffa757c1de5a65
ARG MODULE_VERSION=0.0.4
ARG MODULE_NAME=ngx_http_proxy_connect_module

RUN cd /usr/src && \
    curl -L "https://github.com/chobits/ngx_http_proxy_connect_module/archive/v${MODULE_VERSION}.tar.gz" -o "v${MODULE_VERSION}.tar.gz" && \
    echo "${MODULE_CHECKSUM}  v${MODULE_VERSION}.tar.gz" | shasum -c && \
    tar -zxC /usr/src -f v${MODULE_VERSION}.tar.gz && \
    cd /usr/src && \
    mv ${MODULE_NAME}-${MODULE_VERSION}/ ${MODULE_NAME} && \
    cd /usr/src/nginx && \
	patch -p1 < ../ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_1018.patch && \
    CONFARGS=$(nginx -V 2>&1 | sed -n -e 's/^.*arguments: //p') \
    CONFARGS=${CONFARGS/-Os -fomit-frame-pointer -g/-Os} && \
    echo $CONFARGS && \
    ./configure --with-compat $CONFARGS --add-dynamic-module=../${MODULE_NAME}/ && \
    make -j $(nproc) && make install && make modules && ls -l /usr/src/nginx/objs
    
FROM scratch

COPY --from=Builder /usr/src/nginx/objs/ngx_http_proxy_connect_module.so /

COPY --from=Builder /usr/sbin/nginx /nginx
